version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boutsdefisel
      MYSQL_USER: boutsdefisel
      MYSQL_PASSWORD: boutsdefisel
    ports:
      - "3309:3306"
  
  backend:
    depends_on:
      - db
    build: './backend'
    command: npm run debug
    ports:
      - "7070:7070"
      - "9222:9222"
    links:
      - db:db
    volumes:
      - ./backend/app:/app

  frontend:
    depends_on:
      - backend
    build: './frontend'
    ports:
      - "8080:80"
    volumes:
      - ./frontend/app:/app
    links:
      - backend:backend